- name: Get Server Info
  gather_facts: no
  hosts: windowsServer
  tasks:

     - name: Memoria
       win_shell: "Get-WMIObject Win32_OperatingSystem | select __server,@{n='Resource';Expression={'MEM'}},@{n='Memory';Expression = {[math]::round(((($_.TotalVisibleMemorySize-$_.FreePhysicalMemory)*100)/$_.TotalVisibleMemorySize), 2)}},@{n='Statdate';Expression = {'{0:20y-M-d H:mm:ss}' -f (get-date)}} | Sort-Object driveletter | ConvertTo-Csv -NoTypeInformation | Select-Object -Skip 1"

     - name: Cpu
       win_shell: "Get-WMIObject  win32_Processor  | select __server,@{n='Resource';Expression={'CPU'}},LoadPercentage,@{n='Statdate';Expression = {'{0:20y-M-d H:mm:ss}' -f (get-date)}} | Sort-Object driveletter | ConvertTo-Csv -NoTypeInformation | Select-Object -Last 1"

     - name: Disco
       win_shell: "Get-WmiObject Win32_Volume | Where { $_.drivetype -eq '3' -and $_.driveletter} | Select-Object __server, driveletter,@{Name='freespace';Expression={[math]::round($_.freespace/1024,2)} },@{Name='capacity';Expression={[math]::round($_.capacity/1024,2)}},@{n='Statdate';Expression = {'{0:20y-M-d H:mm:ss}' -f (get-date)}} | Sort-Object driveletter | ConvertTo-Csv -NoTypeInformation | Select-Object -Skip 1"
