---
- name: Creating the users
  user:
    name: "{{ name }}"
    password: "{{ 'Pass.001' | password_bash('sha512') }}"
    comment: "{{ sfull }}"
    shell: /bin/bash
    group: wheel
    groups: wheel
    home: /home/{{ sname }}
